---
- name: install httpd
  hosts: all
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: start service
      service:
        name: httpd
        state: started
    - name: stop httpd
      service:
        name: httpd
        state: stopped
    - name: enable httpd
      service: 
        name: httpd
        enabled: yes
    - name: restart httpd
      service: 
        name: httpd
        state: restarted 