---
- name: installing nginx
  hosts: all 
  become: true 
  tasks: 
    - name: installing nginx 
      yum: 
        name: nginx 
        state: latest 
    - name: start nginx service 
      service: 
        name: nginx 
        state: started 
    - name: stopp nginx 
      service: 
        name: nginx 
        state: stopped 
    - name: enable nginx 
      service: 
        name: nginx 
        enabled: yes 
    - name: restatrting nginx 
      service: 
        name: nginx 
        state: restarted 