--- 
- name: creating a user by outside file 
  hosts: all 
  become: true 
  vars_files: 
    - user.yml 
  tasks: 
    - name: creating a user {{user}}
      user: 
        name: "{{user}}"
        