--- 
- name: install tomcat service 
  hosts: all 
  become: true 
  tasks: 
    - name: install java
      apt: 
        name: java 
        state: latest 
    - name: download tomcat 
      get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /usr/local
    - name: extract packages 
      unarchive: 
        src: /usr/local/apache-tomcat-9.0.65.tar.gz
        dest: /usr/local 
        remote_src: yes 
    - name: start tomcat service 
      shell: nohup /usr/local/apache-tomcat-9.0.65/bin/startup.sh 